### ISSUE TITLE
Investigate changes to 'lsblk'

### ISSUE THREAD

**Issue by agrover** [stratis-storage/project#122]
We updated libblkid for Stratis but we should also check to see if lsblk needs related changes, specifically maybe to the TYPE or FSTYPE fields.

**Comment by mulkieran** [comment]
Reading this more carefully, I realize that this is about extending the capabilities of lsblk, not about stratisd device discovery, so moving to project.

**Comment by rhmcruiser** [comment]
Is the below also an expected behavior or should we have the output of lsblk be improved. 
In below the block devices in the stratis pool show repetitive stats in lsblk . Is this ok?  

block devices part of the stratis pool are sdb and sdc
[root@vm37-224 ~]# stratis pool
Name     Total Physical Size  Total Physical Used
my-pool                4 GiB              602 MiB
[root@vm37-224 ~]# 

[root@vm37-224 ~]# stratis blockdev
Pool Name  Device Node  Physical Size  State  Tier
my-pool    /dev/sdb             2 GiB  InUse  Data
my-pool    /dev/sdc             2 GiB  InUse  Data

lsblk output

sdb                                                                                           8:16   0    2G  0 disk    
└─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-physical-originsub                     253:2    0    4G  0 stratis 
  ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thinmeta                        253:3    0   16M  0 stratis 
  │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool                      253:6    0    4G  0 stratis 
  │   └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7    0    1T  0 stratis /mnt/stratis
  ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thindata                        253:4    0    4G  0 stratis 
  │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool                      253:6    0    4G  0 stratis 
  │   └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7    0    1T  0 stratis /mnt/stratis
  └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-mdv                             253:5    0   16M  0 stratis 
sdc                                                                                           8:32   0    2G  0 disk    
└─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-physical-originsub                     253:2    0    4G  0 stratis 
  ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thinmeta                        253:3    0   16M  0 stratis 
  │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool                      253:6    0    4G  0 stratis 
  │   └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7    0    1T  0 stratis /mnt/stratis
  ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thindata                        253:4    0    4G  0 stratis 
  │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool                      253:6    0    4G  0 stratis 
  │   └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7    0    1T  0 stratis /mnt/stratis
  └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-mdv                             253:5    0   16M  0 stratis

**Comment by mulkieran** [comment]
> Is the below also an expected behavior or should we have the output of lsblk be improved.
> In below the block devices in the stratis pool show repetitive stats in lsblk . Is this ok?
> 
> block devices part of the stratis pool are sdb and sdc
> [root@vm37-224 ~]# stratis pool
> Name Total Physical Size Total Physical Used
> my-pool 4 GiB 602 MiB
> [root@vm37-224 ~]#
> 
> [root@vm37-224 ~]# stratis blockdev
> Pool Name Device Node Physical Size State Tier
> my-pool /dev/sdb 2 GiB InUse Data
> my-pool /dev/sdc 2 GiB InUse Data
> 
> lsblk output
> 
> sdb 8:16 0 2G 0 disk
> └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-physical-originsub 253:2 0 4G 0 stratis
> ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thinmeta 253:3 0 16M 0 stratis
> │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool 253:6 0 4G 0 stratis
> │ └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7 0 1T 0 stratis /mnt/stratis
> ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thindata 253:4 0 4G 0 stratis
> │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool 253:6 0 4G 0 stratis
> │ └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7 0 1T 0 stratis /mnt/stratis
> └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-mdv 253:5 0 16M 0 stratis
> sdc 8:32 0 2G 0 disk
> └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-physical-originsub 253:2 0 4G 0 stratis
> ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thinmeta 253:3 0 16M 0 stratis
> │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool 253:6 0 4G 0 stratis
> │ └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7 0 1T 0 stratis /mnt/stratis
> ├─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-thindata 253:4 0 4G 0 stratis
> │ └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-thinpool-pool 253:6 0 4G 0 stratis
> │ └─stratis-1-dbbd9c30babd4e8dba103fb376555996-thin-fs-ab4f6b66ce11475da6a09cf20f4fc304 253:7 0 1T 0 stratis /mnt/stratis
> └─stratis-1-private-dbbd9c30babd4e8dba103fb376555996-flex-mdv 253:5 0 16M 0 stratis

That's just how lsblk works, and is really beyond Stratis's control. lsblk;s output treats the storage track as tree structured, but it really needs to be viewed as a DAG (directed acyclic graph).

I believe that there is some work going on to make it possible for users to see a less duplicated and possibly richer representation of the storage stack, encoding perhaps the different kinds of relationships between the various storage devices, but you'ld have to go to the lsblk people to find out more.

**Comment by karelzak** [comment]
This is how the kernel sees dependencies between the devices. Don't forget the same device is possible to use more than once in the tree, so the relation is not 1:N (like we have for disk->partition), but it's N:M.

I have a more readable example (thin-pool on loop0 with external snapshot device on loop1):
```
$ lsblk -oNAME /dev/loop1 /dev/loop0
NAME
loop0
├─test-thin-metadata
│ └─test-thin-pool
│   ├─test-thin
│   └─test-thin-extsnap
└─test-thin-data
  └─test-thin-pool
    ├─test-thin
    └─test-thin-extsnap
loop1
└─test-thin-extsnap
```

in this case, test-thin and test-thin-extsnap depend on test-thin-metadata as well as on test-thin-data, so we repeat it. 

Yes, it's confusing for end-users, this is the reason why I have implemented --merge:

```
$ lsblk --merge -oNAME /dev/loop1 /dev/loop0
       NAME
       loop0
   ┌┈▶ ├─test-thin-metadata
   └┬▶ └─test-thin-data
┌┈▶ └┈┈test-thin-pool
┆      └─test-thin
└┬▶    loop1
 └┈┈┈┈┈test-thin-extsnap
```
now nothing is duplicated and N:M relations are described by additional lines. Try --merge for your stratis ;-)

**Comment by mulkieran** [comment]
Thx! Closing.
