### ISSUE TITLE
Cockpit support

### ISSUE THREAD

**Issue by agrover** [stratis-storage/project#140]
https://cockpit-project.org/ is the current graphical administration interface for servers, so Stratis configuration should be supported there.

Related issues:
- [x] https://github.com/stratis-storage/project/issues/216
- [x] https://github.com/stratis-storage/project/issues/219
- [x] https://github.com/stratis-storage/stratisd/issues/1377
- [x] https://github.com/stratis-storage/stratisd/issues/2179
- [x] https://github.com/stratis-storage/stratisd/issues/2191
- [ ] https://github.com/stratis-storage/stratisd/issues/2194
- [x] https://github.com/stratis-storage/stratisd/issues/2219

**Comment by mvollmer** [comment]
I have this now: https://github.com/cockpit-project/cockpit/pull/14109

The main issue I found is that there don't seem to be any D-Bus signals coming out of the org.storage.stratis2 API. Indeed, the introspection data returned by stratisd does not mention any signals at all, not even the signals of the standard ObjectManager and Properties interfaces. Right now, I'd call this is a blocker, but maybe I am misunderstanding things.

Other issues:

 - The symlinks in /stratis/ are not managed by udev, and are for example unknown to UDisks2. This complicates processing slightly since Cockpit needs to read them explicitly in order to match Stratis blockdevs to UDisks2 objects. I hear that you are moving away from this, true? 

- I don't clearly see the motivation for the FetchProperties interface. It looks like a weaker version of the standard Properties interface with no added value but some drawbacks (like no change notifications, and not allowing per-interface properties). Could I convince you to just use the Properties interface?

- Method calls don't use the standard D-Bus error replies but include codes and messages in their result signature. That also looks unmotivated to me, but we can of course easily work with either style.

**Comment by jbaublitz** [comment]
> The symlinks in /stratis/ are not managed by udev, and are for example unknown to UDisks2. This complicates processing slightly since Cockpit needs to read them explicitly in order to match Stratis blockdevs to UDisks2 objects. I hear that you are moving away from this, true?

I can at least comment on the udev-managed symlinks. There is a PR with proposed changes here stratis-storage/stratisd#2020. This would move management mostly into a udev rule and the symlinks would be under `/dev/stratis`.

**Comment by jbaublitz** [comment]
> I don't clearly see the motivation for the FetchProperties interface. It looks like a weaker version of the standard Properties interface with no added value but some drawbacks (like no change notifications, and not allowing per-interface properties). Could I convince you to just use the Properties interface?

@mvollmer I have a question for you on this point. The rationale for this is primarily that we need to expose some properties where fetching them can fail. If fetching them fails, the whole call to `GetManagedObjects()` will also fail and stratisd becomes essentially unusable. Users can no longer list any information about the resources that they have created. I've been curious if there's a better way to handle this using existing D-Bus infrastructure but I have been unable to find any mention of how to handle this case in the D-Bus specification docs or in other articles that I've read on D-Bus. Is there an alternative that you've seen given how much you've worked with D-Bus that protects us from getting into a completely unusable state simply because a property gets into a failure state?

**Comment by agrover** [comment]
Be easier to just not fail getting property values.  Maybe cache prop vals and return cached if fetch fails. Stale is better than nothing. Or, one value missing is better than the whole thing missing.

**Comment by mvollmer** [comment]
> > I don't clearly see the motivation for the FetchProperties interface. [...]
> 
> @mvollmer I have a question for you on this point. The rationale for this is primarily that we need to expose some properties where fetching them can fail. [...]

With FetchProperties, you encode the failure to compute a value into the value of the property, as `(False, "message")`. You can just do the same with the standard Properties interface.

**Comment by mulkieran** [comment]
Since this is an issue that really requires in-depth discussion, I'm considering it blocked by the other significant work that we need to complete in the next couple of weeks.

**Comment by mulkieran** [comment]
Blocked by #171.

**Comment by mulkieran** [comment]
We should all take a look at the prototype and video; then it'll be time to meet.

**Comment by mulkieran** [comment]
Just one left, but definitely won't be working on that until April.

**Comment by mulkieran** [comment]
Closing this, since there is only one sub-issue left.
