### ISSUE TITLE
rustfmt issue with libcryptsetup CI

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#144]
As seen [here](https://travis-ci.org/stratis-storage/libcryptsetup-rs/jobs/652167818?utm_medium=notification&utm_source=github_status), rustfmt for Rust 1.40.0 requests a change to line up strings after the quotation mark on the line above. This is no longer requested in Rust 1.41.0.

@mulkieran How do we want to proceed? I think the first order of action is to move the CI toolchain in libcryptsetup-rs up to stable (1.41.0) and I'll make sure to take care of that at the same time as our other crates in the future. However, is this something we should open as an issue with rustfmt? I don't recall what the conditions are where you've done that in the past.

**Comment by mulkieran** [comment]
Our development tool chain generally lags stable for a bit. We should be moving it up a version in a day or two. We were held up by the package's slow progress into Fedora 30. We could consider defining our development toolchain differently; that would require having all the team use rustup.

If you can satisfy 1.40 rustfmt w/out breaking 1.41 rustfmt, you might as well do that. Unlike black, rustfmt does a lot of very hard to understand holding on to previous formatting, so that is worth a try.

If that works, then there is no point in filing a bug against rustfmt, they'll simply consider themselves to have made the formatting less restrictive. Otherwise, you might want to file a bug, since they have a stability guarantee that they would be breaking, but likely they won't want to do anything about it, since it's already made its way into stable.

**Comment by jbaublitz** [comment]
Ok will do. I can easily move back to 1.40.0 with rustup and use rustfmt. Closing.
