### ISSUE TITLE
clevis support

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#192]
We are interested in also allowing an NBDE mechanism for unlocking devices in a pool.

**Comment by mulkieran** [comment]
@jbaublitz Please go ahead and add any additional comments.

**Comment by jbaublitz** [comment]
My thoughts here after looking at the Clevis source code are around a few particular points:
1. Because Clevis uses cryptsetup just like stratisd uses libcryptsetup, the integration at a format level should not be too challenging.
2. Because Clevis seems to bind to an existing LUKS device and populates a new keyslot, we would need some kind of existing keyslot to allow Clevis to make changes to the keyslots. This is a requirement that I've seen during my interactions with libcryptsetup; you either need to have the volume key in memory using the programmatic interface, or an existing key available to be passed in as a parameter/path to a keyfile to make changes. My current thought is to statically assign the next available keyslot (index 2) for optional Clevis support.
3. I have a concern around passing the existing passphrase as a command line parameter to the Clevis executable for binding. It would be excellent if we could find a way to get cryptsetup to add a new key using the existing key that the user has specified in Stratis from the keyring. Unfortunately, this does not seems to be an option with the cryptsetup executable so my suggestion here would be the following:
  a. Read the key from the keyring into our `SafeMemHandle` structure or something comparable.
  b. When invoking Clevis, coerce this to a byte slice so no new copies of the key are made in memory.
  c. From here we need to discuss with the Clevis team how they handle non-unicode passphrases as we do support those and if we're only allowed to pass in valid unicode for a passphrase, at the very least we'll have to figure out how to enforce that restriction for devices on which a user will later want to enable NDBE. If Clevis allows keyfiles with non-unicode contents, we will have to figure out how to integrate that with the keyring.
  d. After that conversation is resolved, we will choose the appropriate way to convert to a `&str` type (either checked for valid unicode or not) which we can pass into the process invocation using something like `std::process::Command`.
4. We should also get more information on the risk of leaving copies of the key in memory during this process.

**Comment by mulkieran** [comment]
@jbaublitz Is there any way we can make use of the method ```crypt_volume_key_get()```? stratisd should be able to make use of the Stratis key in order to get the volume key, I think. Then it could use ```crypt_keyslot_add_by_volume_key()``` to set up the NBDE keyslot.

This functionality would be reusable, also, in the case where both were set up at once via ```crypt_format``` on initialization.

**Comment by jbaublitz** [comment]
@mulkieran Yes, I'm in agreement with the edit.

**Comment by mulkieran** [comment]
Rough agenda:

- [ ] Practical aspects of getting the passphrase in the kernel keyring to Clevis
- [ ] Requirements for TPM2 as implemented now
- [ ] Possible Rust API in future?
- [ ] Recommendations for unlocking policy. The current plan is for the D-Bus API to present a per-pool interface which will allow the unlocking mechanism, NBDE or kernel keyring to be specified.

**Comment by jbaublitz** [comment]
@mulkieran It appears that if we pipe passphrases to cryptsetup, the passphrase input will end once a newline is reached. This will be a big problem in the case of our accepted keyfile format but not our interactive input format so we should potentially consider reading the key into memory-backed temporary files that are owned by and only readable by root for the time being as a possible alternative. This would prevent keys from being written plaintext to disk and we could wipe the memory backing the file after it's read from. It seems like that would be the most careful treatment of sensitive data that also works with our constraints.

**Comment by jbaublitz** [comment]
Currently working on a prototype of keyfile handling for clevis integration.

**Comment by mulkieran** [comment]
Done!
