### ISSUE TITLE
Use cargo outdated command to ease Fedora packaging process

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#201]
Currently with the way Fedora packages Rust libraries, letting dependencies lag too far behind can cause build failures on koji. We should use `cargo outdated` to detect the `Compat` version of all of our dependencies. `Compat` indicates the most recent version that cargo will pull in automatically given what version we've pinned at in `Cargo.toml`. From there, we should check against:

https://kojipkgs.fedoraproject.org/repos/rawhide/latest/x86_64/pkglist

and parse that file to determine if:
1. The package is available in Fedora.
2. Our `Compat` version of the dependency is available in Fedora.

If either condition is not satisfied, Fedora cannot build stratisd and so we will have to update. Providing an automated way to track this down will be beneficial from a code maintenance standpoint.

**Comment by mulkieran** [comment]
I think this applies to all Stratis Rust packages, not just stratisd. libcryptsetup-rs is certainly in a good state, because it just got released in Fedora, but devicemapper-rs is uncertain.

In the best case, we'ld like to get the information and take the steps described in this issue on devicemapper-rs before cutting a new release, rather than struggling with problems when trying to make the new Fedora release that should follow.

The condition for raising the version of a dependency specified in Cargo.toml seems just right to me.

I have a couple of questions:
* What is the context in which we would run this script? Should we make it a timed Jenkins job, once ready? Once a day, or even once a week might be enough.
* Who provides the link and how stable is it? Do we know what other entities use it as their source for this information?

**Comment by jbaublitz** [comment]
> I think this applies to all Stratis Rust packages, not just stratisd. libcryptsetup-rs is certainly in a good state, because it just got released in Fedora, but devicemapper-rs is uncertain.
> 
> In the best case, we'ld like to get the information and take the steps described in this issue on devicemapper-rs before cutting a new release, rather than struggling with problems when trying to make the new Fedora release that should follow.
> 
> The condition for raising the version of a dependency specified in Cargo.toml seems just right to me.
> 
> I have a couple of questions:
> 
>     * What is the context in which we would run this script? Should we make it a timed Jenkins job, once ready? Once a day, or even once a week might be enough.

I would say once a day should be plenty. I think this will mainly come up before releasing so that should be enough time to fix a potential issue. Even once a week would probably be fine.

> 
>     * Who provides the link and how stable is it? Do we know what other entities use it as their source for this information?

This is the official list of packages in the koji rawhide repo itself. Given that this is considered the repository to enable once koji successfully builds a package for rawhide before a compose is released, I would consider this to be a source of truth for which packages are available in rawhide. The only note is that we should perhaps make the repo we choose flexible enough to also work for previous versions of Fedora if you see this being a problem too. I'm not sure how often crate versions get bumped in already released versions of Fedora.

**Comment by mulkieran** [comment]
Ok! That seems good. We should focus on rawhide first thing, and we can worry about prior versions later.

**Comment by mulkieran** [comment]
Resolved by https://github.com/stratis-storage/stratisd/pull/2280
