### ISSUE TITLE
Letting set key --capture-key command timeout can lock terminal

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/project#237]
OS F33
Stratis version: 2.1, 2.2

When running stratis set key testkey --capture-key, and then letting the command timeout (2 minutes) by not providing a passphrase.  The error below is seen:

[root@localhost ~]# stratis key set testkey --capture-key
Enter desired key data followed by the return key:
Execution failed:
stratis attempted communication with the daemon, stratisd, over the D-Bus, but stratisd did not respond in the allowed time. 

After this the terminal is not usable.  The reset command doesn't correct this condition.

**Comment by mulkieran** [comment]
We should consider only version 2.2. In version 2.2, if you kill the daemon, then reset will work.

**Comment by jbaublitz** [comment]
This is a complicated problem because what is happening is the following:

The daemon receives the file descriptor and tries a blocking read. The connection then disconnects, but the server is unaware that it disconnected so it continues blocking for data on stdin. This means that stratis-cli's stdin is still being read from stratisd after the connection times out. In my tests, hitting return a number of times eventually restored the terminal's normal operations, and the reason for this is that once stratisd reads any data from stdin, it will cease to block on that read and will store whatever data it gets from that read in the keyring. Subsequently, it will then restore the terminal's normal operations.

First off, @drckeefe, can you confirm that on your machine hitting return a number of times will restore normal terminal operations?

@mulkieran This is actually a really tricky problem because we have no awareness of the client timeout on the D-Bus server side. If we did, this would be relatively simple: block on the file descriptor read until either the timeout has been reached or data has been provided then close the file descriptor. Because we don't have any information on the timeout, we're in kind of a difficult place. Even if we did the terminal setting handling in stratis-cli this would actually still be a problem, just not a problem that's visible to the user. The server side would still be reading stdin until data is received on stdin even if the client reset the terminal back to its normal "cooked" mode. I'm not really sure if there are very many good options here. Ideally, we'd want a way to signal from stratis-cli to stratisd that it should stop reading from stdin but the only way I can think of doing that is an operating system signal which is not ideal at all and would also be challenging for people using our API to implement correctly. I'll have to think about this more because it doesn't seem like we have a very good option here. One potential stop-gap is providing the client-side timeout as a parameter to the server. This would at least allow us to reset the file descriptor settings and close the file descriptor by the time control returns to the shell on the client side.
