### ISSUE TITLE
If a pool is in an inconsistent state stratisd should mark it as requiring maintenance and refuse to do mutating operations

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#310]
After some discussion:

1. An obvious cause of inconsistent state is a failure of a rollback operation. A likely failure is failure to rollback an unbind action.
2. Exposing as a D-Bus property this information is appropriate. Using the information in the CLI in display methods is appropriate.
3. Limiting the operations that can be performed on the pool is appropriate.

Note that there are other situations, for example if the pool's thinpool has failed, which are similar, but not the same.

**Comment by jbaublitz** [comment]
I had one question about this issue. How do we want to handle inconsistent metadata for read operations? This is relevant for the `Report` interface and some D-Bus properties.

With the `Report` interface, we could easily either return a string for inconsistent properties like `INCONSISTENT` or even report all values present in the pool. I'm not sure which would be preferable here, but both should be relatively easy given that we're returning JSON.

With the D-Bus properties, if we're making the report interface report inconsistent properties, we could easily return a new application level error indicating that the properties are inconsistent. I think that all of the metadata for encryption operations is contained in `FetchProperties` which can easily return an error so one option is to report a message about the property being inconsistent. I feel like the other option here, like with the `Report` interface, is to return both values given that we are returning a variant for the value so it could be a single or multiple values.

I'd also like to mark methods on the engine that can get into an inconsistent state at the type level with some kind of enum called `MaybeInconsistent`. That seems like a better way to handle this than using `Option` or `Result` so that we can add to it as needed.

Do you have any thoughts on this @mulkieran?

**Comment by mulkieran** [comment]
@jbaublitz Is https://github.com/stratis-storage/project/issues/310#issuecomment-848772543 about inconsistency for a single device or for multiple devices within a pool?

**Comment by jbaublitz** [comment]
@mulkieran This would be inconsistency between multiple devices in a pool. After looking at our report interface, this might be less of an issue given that key descriptions and Clevis information is defined per block device so we can simply report exactly which devices are associated with which key descriptions even if they are inconsistent. This, however, is a problem that we will need to solve for properties on the D-Bus given that the key description is defined on the pool so if a rollback operation fails, we may have two key descriptions set for a pool. We can either return two key descriptions indicating inconsistency or return a value that is something like `INCONSISTENT`.

**Comment by mulkieran** [comment]
Closed by merged PRs.
