### ISSUE TITLE
Figure out how to write cleanup actions for blackbox tests that are independent of the CLI and, if possible, independent of the daemon as well

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#81]
They _must_ be independent of the CLI, because we can not run the old CLI to test the daemon.

It would be good to make them independent of the daemon as well, as the daemon may have failed the test and won't be able to do the necessary cleanup, because it's internal structures don't match reality, but that is less important.

**Comment by mulkieran** [comment]
@jbaublitz, @bgurney-rh - Regarding the second part, not depending on the daemon for cleaning up after tests, you'll have to use your judgement. If the test has gone correctly implying the daemon is working, then it might still make sense to use the daemon to do the cleanup, and it might be the least risky and most efficient. If the test has failed, then it is less likely that the daemon is in a good state, and more likely that trying to clean up via the daemon will fail. Then the question is, how much do we care about cleanup after a test has already failed? We still would like it to work, of course, but is it the most important thing. The other question is, what if daemon-based cleanup fails even though the test succeeded? How should we address that?

**Comment by bgurney-rh** [comment]
I'm imagining an approach similar to teardown.sh (in the ci repo), where it does the following:
- Terminate any remaining stratisd process (except instead of the "target/debug/stratisd" one, it'll have to be the installed stratisd)
- Use "dmsetup remove" to remove all Stratis-based devices, from top to bottom
- Execute "wipefs -a" on the test devices specified in /etc/stratis/test_config.json

This is still running on the assumption that the test system does not have any device-mapper devices in a "normal state" (i.e.: the OS partitions are plain partitions).

Right now, in stratisd, the teardown.sh script is only executed after a failed test.  For the blackbox test, I suppose there could be a post-success check to ensure that there aren't any remnant devices (and perhaps find a way to "fail" the test if there are any "leaked devices").
