### ISSUE TITLE
Wants to create /stratis, can't on ostree-managed systems

### ISSUE THREAD

**Issue by cgwalters** [stratis-storage/project#95]
```
[root@coreos ~]# strace -f /usr/libexec/stratisd 
...
mkdir("/stratis", 0777)                 = -1 EPERM (Operation not permitted)
[root@coreos ~]# rpm-ostree status -b
State: idle
AutomaticUpdates: disabled
BootedDeployment:
* ostree://fedora:fedora/x86_64/coreos/testing-devel
                   Version: 30.20190730.dev.1 (2019-07-30T20:56:45Z)
          BootedBaseCommit: 885e85a768b15a32abc6d2ed05ce7ec99de5f77da58993f4c35ade903b5e5a98
                    Commit: e0b175edf6268dbe305d0d1c93730756285f9199a8ebef2d0bf0caa976665818
              GPGSignature: (unsigned)
           LayeredPackages: stratis-cli
[root@coreos ~]# 
```

Mutating the toplevel `/` isn't permitted on ostree-based systems.  A bit more information [here](https://github.com/stratis-storage/stratisd/issues/new).

What's stored there?  Why can't it be `/var/stratis`?  Or possibly `/etc/stratis` if it's more like LVM's `/etc/lvm` (on that topic see also [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1366584)).

**Comment by AdrianKoshka** [comment]
Any progress on this? As a recent fedora silverblue convert (Fedora 31 upgrade blew up), this is annoying.

**Comment by drckeefe** [comment]
Opened a bug in bugzilla to track this issue for RHEL development. 
https://bugzilla.redhat.com/show_bug.cgi?id=1798244

**Comment by jbaublitz** [comment]
I've done some preliminary work on this and here's what I've found so far:

#### Option 1
Work with the systemd team to relinquish management of stratis devices in fstab to us and write our own generator. As it stands, we would be battling with their generated mount file at generation time and so we would need to coordinate with them. I have a prototype of the generator in Rust (the documentation recommended C so I chose Rust).
##### Pros:
* This is a relatively simple approach once we can get the `systemd-fstab-generator` to ignore `/dev/stratis` entries. We simply generate mount files and device files for the resolved symlink and things work as expected.
##### Cons:
* Because the symlink is not recognized by udev, we need to resolve it to the device the symlink points to. This is a little less natural and straightforward than simply registering it with udev. Generating a device file for the symlink does not work because device files seem to only work with what is managed by udev.

#### Option 2
Use udev to manage the symlinks instead of the `devlinks` module. This actually can be done with a workaround for the issue of not having the pool and filesystem name at the time of udev firing (mentioned in stratis-storage/stratisd#1258). udev rules can call scripts and I have a prototype of a combination of a script and a udev rule that queries the stratisd D-Bus API to obtain the correct pool and filesystem name and then creates the same `/dev/stratis/<POOL_NAME>/<FS_NAME>` symlink all through udev.
##### Pros:
* This is a solution using existing tools as intended so in terms of integrating with systemd and udev, we will be within the realm of supported use.
* This means that we will not have to generate any unit files (I have tested that the generated .device files for a symlink created by udev work properly).
##### Cons:
* This will take a lot of careful work when removing the `devlinks` module. To test this, I commented out all uses of the `devlinks` module and things almost worked with the caveat of Stratis failing to create a filesystem if `/dev/stratis` was not already present. Things did, however, work when I manually added `/dev/stratis` prior to creating the filesystem. udev will remove `/dev/stratis` if it is empty and it will be empty if all filesystems are destroyed so we will have to reason about our expectations of `/dev/stratis` being present in the code if we take this approach.

**Comment by cgwalters** [comment]
> Mutating the toplevel / isn't permitted on ostree-based systems. 

I thought about this more and I think it'd also fine if for now if we just special-case Stratis to write to `/sysroot/stratis`.  It's actually similar to `/sysroot/ostree` - it's *global* state in many ways independent of a particular operating system.   The argument here is quite similar to LVM, which stores some state in `/etc/lvm` but a lot of the "structure" is actually stored at the block device level.

Imagine having a dual-booting system (whether that's Ubuntu+Fedora or RHEL+Fedora or whatever) that share `/home` on LVM - you don't want the LVM state stored in `/etc` in the individual OS, you want it shared.

Anyways we [have the immutable bit set on /sysroot too](https://github.com/coreos/coreos-assembler/pull/737) but eh, Stratis could just do on startup: `if ! -d /sysroot/stratis; then chattr -i /sysroot; mkdir /sysroot/stratis; chattr +i /sysroot` or so.  (Yes, there's a race if anything else wants to do this but so far there's nothing else)

**Comment by jbaublitz** [comment]
@cgwalters While we definitely want stratisd to work with ostree, we ran into some other problems by not having it in `/dev/stratis` as that seems to be the ideal location for our symlinks. For now, I have a working prototype (in the linked PR above) to move some of our logic into a udev rule and let udev manage our symlinks for us.
